services:
  server:
    container_name: itemsadder_server
    image: ghcr.io/xmikux/itemsadder-image:latest
    volumes:
      - type: bind
        source: ${PWD}/external
        target: /app/external
      - type: bind
        source: ${PWD}/Resourcepack/contents
        target: /app/plugins/ItemsAdder/contents
      - type: bind
        source: ${PWD}/output
        target: /app/plugins/ItemsAdder/output
    ports:
      - 25575:25575
    environment:
      - RCON_ENV