name: Release | Version Test

on:
  workflow_dispatch: {}

jobs:
  version-gen-beta:
    name: Version Generator
    uses: ./.github/workflows/resuable_version.yml
    if: |
      github.repository == 'xMikux/Slimefun-Resourcepack'
    with:
      release_type: "beta"
  version-gen-release:
    name: Version Generator
    uses: ./.github/workflows/resuable_version.yml
    if: |
      github.repository == 'xMikux/Slimefun-Resourcepack'
    with:
      release_type: "release"
  generate-version-summary:
    name: Generate Version Summary
    runs-on: ubuntu-latest
    needs: [ version-gen-beta, version-gen-release ]
    steps:
      - name: Act - Summary
        run: |
          echo "# Version Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Current Version: `${{ needs.version-gen-release.outputs.version_semver_current_name }}`" >> $GITHUB_STEP_SUMMARY
          echo "- Next Version: `${{ needs.version-gen-release.outputs.version_semver_next_name }}`" >> $GITHUB_STEP_SUMMARY
          echo "- SHA Version: `${{ needs.version-gen-release.outputs.version_sha_name }}`" >> $GITHUB_STEP_SUMMARY
          echo "- PackFormat - Beta: `${{ needs.version-gen-beta.outputs.pack_version_name }}`" >> $GITHUB_STEP_SUMMARY
          echo "- PackFormat - Release: `${{ needs.version-gen-release.outputs.pack_version_name }}`" >> $GITHUB_STEP_SUMMARY
