name: Resuable | Modrinth Release

on:
  workflow_call:
    inputs:
      release_type:
        type: string
        required: false
        default: "beta"
      version:
        type: string
        required: true
    secrets:
      MODRINTH_TOKEN:
        required: true

jobs:
  modrinth_release:
    name: Release Modrinth
    runs-on: ubuntu-latest
    steps:
      -
        name: Artifact - Download Slimefun Resourcepack
        uses: actions/download-artifact@v4
        with:
          path: workdir
          merge-multiple: true
      -
        name: Name - Fix naming
        run: |
          mv workdir/pack.zip Slimefun-ResourcePack.zip
          mv workdir/*.zip .
          ls -alh
      -
        name: Modrinth - Relase Beta
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: TznkVJky
          modrinth-featured: false
          version: ${{ inputs.version }}
          version-type: beta
          loaders: minecraft
          game-versions: ">=1.19"
          dependencies: |
            otVJckYQ(recommended)
          files: |
            Slimefun-ResourcePack.zip
            item-models.zip
            ia-addons.zip
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
